const classSkills = {
    Envoy: [
      "Bluff",
      "Computers",
      "Culture",
      "Diplomacy",
      "Disguise",
      "Intimidate",
      "Perception",
      "Profession",
      "Sense Motive",
    ],
    Mechanic: [
      "Athletics",
      "Computers",
      "Engineering",
      "Medicine",
      "Perception",
      "Physical Science",
      "Piloting",
      "Profession",
    ],
    Mystic: [
      "Culture",
      "Diplomacy",
      "Life Science",
      "Medicine",
      "Mysticism",
      "Perception",
      "Profession",
      "Sense Motive",
      "Survival",
    ],
    Operative: [
      "Acrobatics",
      "Athletics",
      "Bluff",
      "Computers",
      "Culture",
      "Disguise",
      "Engineering",
      "Intimidate",
      "Medicine",
      "Perception",
      "Piloting",
      "Profession",
      "Sense Motive",
      "Sleight of Hand",
      "Stealth",
      "Survival",
    ],
    Solarian: [
      "Acrobatics",
      "Athletics",
      "Diplomacy",
      "Intimidate",
      "Mysticism",
      "Perception",
      "Physical Science",
      "Profession",
      "Sense Motive",
      "Stealth",
    ],
    Soldier: [
      "Acrobatics",
      "Athletics",
      "Engineering",
      "Intimidate",
      "Medicine",
      "Piloting",
      "Profession",
      "Survival",
    ],
    Technomancer: [
      "Computers",
      "Engineering",
      "Life Science",
      "Mysticism",
      "Physical Science",
      "Piloting",
      "Profession",
    ],
    Biohacker: [
      "Bluff",
      "Computers",
      "Culture",
      "Diplomacy",
      "Engineering",
      "Life Science",
      "Medicine",
      "Perception",
      "Physical Science",
      "Profession",
      "Sense Motive",
      "Sleight of Hand",
    ],
    Vanguard: [
      "Acrobatics",
      "Athletics",
      "Culture",
      "Diplomacy",
      "Intimidate",
      "Life Science",
      "Medicine",
      "Mysticism",
      "Perception",
      "Profession",
      "Stealth",
      "Survival",
    ],
    Witchwarper: [
      "Acrobatics",
      "Bluff",
      "Culture",
      "Diplomacy",
      "Intimidate",
      "Mysticism",
      "Physical Science",
      "Profession",
    ],
  };

  export default classSkills