const classProgressionTable = {
  Biohacker: [
    {
      level: "1",
      bab: "0",
      fort: "2",
      ref: "0",
      will: "0",
      special:
        "Biohacks, custom microlab, injection expert, primary field of study, scientific method",
    },
    {
      level: "2",
      bab: "1",
      fort: "3",
      ref: "0",
      will: "0",
      special: "Injection expert +1, theorem",
    },
    {
      level: "3",
      bab: "2",
      fort: "3",
      ref: "1",
      will: "1",
      special: "Spark of ingenuity 1/day, weapon specialization",
    },
    {
      level: "4",
      bab: "3",
      fort: "4",
      ref: "1",
      will: "1",
      special: "Theorem",
    },
    {
      level: "5",
      bab: "3",
      fort: "4",
      ref: "1",
      will: "1",
      special:
        "Custom microlab (advanced medkit), primary field of study breakthrough",
    },
    {
      level: "6",
      bab: "4",
      fort: "5",
      ref: "2",
      will: "2",
      special: "Theorem",
    },
    {
      level: "7",
      bab: "5",
      fort: "5",
      ref: "2",
      will: "2",
      special: "Secondary field of study",
    },
    {
      level: "8",
      bab: "6",
      fort: "6",
      ref: "2",
      will: "2",
      special: "Theorem",
    },
    {
      level: "9",
      bab: "6",
      fort: "6",
      ref: "3",
      will: "3",
      special:
        "Custom microlab (medical lab, 90 feet), injection expert +2, spark of ingenuity 2/day",
    },
    {
      level: "10",
      bab: "7",
      fort: "7",
      ref: "3",
      will: "3",
      special: "Theorem",
    },
    {
      level: "11",
      bab: "8",
      fort: "7",
      ref: "3",
      will: "3",
      special: "Secondary field of study breakthrough",
    },
    {
      level: "12",
      bab: "9",
      fort: "8",
      ref: "4",
      will: "4",
      special: "Theorem",
    },
    {
      level: "13",
      bab: "9",
      fort: "8",
      ref: "4",
      will: "4",
      special: "Tertiary field of study",
    },
    {
      level: "14",
      bab: "10",
      fort: "9",
      ref: "4",
      will: "4",
      special: "Theorem",
    },
    {
      level: "15",
      bab: "11",
      fort: "9",
      ref: "5",
      will: "5",
      special: "Spark of ingenuity 3/day",
    },
    {
      level: "16",
      bab: "12",
      fort: "10",
      ref: "5",
      will: "5",
      special: "Theorem",
    },
    {
      level: "17",
      bab: "12",
      fort: "10",
      ref: "5",
      will: "5",
      special:
        "Custom microlab (120 feet), tertiary field of study breakthrough",
    },
    {
      level: "18",
      bab: "13",
      fort: "11",
      ref: "6",
      will: "6",
      special: "Injection expert +3, theorem",
    },
    {
      level: "19",
      bab: "14",
      fort: "11",
      ref: "6",
      will: "6",
      special: "Resolve analysis",
    },
    {
      level: "20",
      bab: "15",
      fort: "12",
      ref: "6",
      will: "6",
      special: "Superserum, theorem",
    },
  ],
  Envoy: [
    {
      level: "1",
      bab: "0",
      fort: "0",
      ref: "2",
      will: "2",
      special: "Envoy improvisation, expertise (1d6), skill expertise",
    },
    {
      level: "2",
      bab: "1",
      fort: "0",
      ref: "3",
      will: "3",
      special: "Envoy improvisation",
    },
    {
      level: "3",
      bab: "2",
      fort: "1",
      ref: "3",
      will: "3",
      special: "Expertise talent, weapon specialization",
    },
    {
      level: "4",
      bab: "3",
      fort: "1",
      ref: "4",
      will: "4",
      special: "Envoy improvisation",
    },
    {
      level: "5",
      bab: "3",
      fort: "1",
      ref: "4",
      will: "4",
      special: "Expertise (1d6+1), skill expertise",
    },
    {
      level: "6",
      bab: "4",
      fort: "2",
      ref: "5",
      will: "5",
      special: "Envoy improvisation",
    },
    {
      level: "7",
      bab: "5",
      fort: "2",
      ref: "5",
      will: "5",
      special: "Expertise talent",
    },
    {
      level: "8",
      bab: "6",
      fort: "2",
      ref: "6",
      will: "6",
      special: "Envoy improvisation",
    },
    {
      level: "9",
      bab: "6",
      fort: "3",
      ref: "6",
      will: "6",
      special: "Expertise (1d6+2), skill expertise",
    },
    {
      level: "10",
      bab: "7",
      fort: "3",
      ref: "7",
      will: "7",
      special: "Envoy improvisation",
    },
    {
      level: "11",
      bab: "8",
      fort: "3",
      ref: "7",
      will: "7",
      special: "Expertise talent",
    },
    {
      level: "12",
      bab: "9",
      fort: "4",
      ref: "8",
      will: "8",
      special: "Envoy improvisation",
    },
    {
      level: "13",
      bab: "9",
      fort: "4",
      ref: "8",
      will: "8",
      special: "Expertise (1d8+2), skill expertise",
    },
    {
      level: "14",
      bab: "10",
      fort: "4",
      ref: "9",
      will: "9",
      special: "Envoy improvisation",
    },
    {
      level: "15",
      bab: "11",
      fort: "5",
      ref: "9",
      will: "9",
      special: "Expertise talent",
    },
    {
      level: "16",
      bab: "12",
      fort: "5",
      ref: "10",
      will: "10",
      special: "Envoy improvisation",
    },
    {
      level: "17",
      bab: "12",
      fort: "5",
      ref: "10",
      will: "10",
      special: "Expertise (1d8+3), skill expertise",
    },
    {
      level: "18",
      bab: "13",
      fort: "6",
      ref: "11",
      will: "11",
      special: "Envoy improvisation",
    },
    {
      level: "19",
      bab: "14",
      fort: "6",
      ref: "11",
      will: "11",
      special: "Expertise talent",
    },
    {
      level: "20",
      bab: "15",
      fort: "6",
      ref: "12",
      will: "12",
      special: "Envoy improvisation, expertise (1d8+4), true expertise",
    },
  ],
  Evolutionist: [
    {
      level: "1",
      bab: "1",
      fort: "2",
      ref: "2",
      will: "0",
      special:
        "Adaptive strike, evolution track, flexible skill, niche, niche ability",
      adaptive_strike: "1d6",
    },
    {
      level: "2",
      bab: "2",
      fort: "3",
      ref: "3",
      will: "0",
      special: "Augmented form, evolutionist adaptation, fulcrum",
      adaptive_strike: "1d6",
    },
    {
      level: "3",
      bab: "3",
      fort: "3",
      ref: "3",
      will: "1",
      special: "Skill boost (+1), weapon specialization",
      adaptive_strike: "1d6",
    },
    {
      level: "4",
      bab: "4",
      fort: "4",
      ref: "4",
      will: "1",
      special: "Evolutionist adaptation",
      adaptive_strike: "1d6",
    },
    {
      level: "5",
      bab: "5",
      fort: "4",
      ref: "4",
      will: "1",
      special: "Evolution drain",
      adaptive_strike: "1d6",
    },
    {
      level: "6",
      bab: "6",
      fort: "5",
      ref: "5",
      will: "2",
      special: "Evolutionist adaptation, skill boost (+2)",
      adaptive_strike: "1d10",
    },
    {
      level: "7",
      bab: "7",
      fort: "5",
      ref: "5",
      will: "2",
      special: "Evolutionary focus (basic)",
      adaptive_strike: "1d10",
    },
    {
      level: "8",
      bab: "8",
      fort: "6",
      ref: "6",
      will: "2",
      special: "Evolutionist adaptation",
      adaptive_strike: "1d10",
    },
    {
      level: "9",
      bab: "9",
      fort: "6",
      ref: "6",
      will: "3",
      special: "Flexible skill, skill boost (+3)",
      adaptive_strike: "2d8",
    },
    {
      level: "10",
      bab: "10",
      fort: "7",
      ref: "7",
      will: "3",
      special: "Evolutionist adaptation, niche ability",
      adaptive_strike: "2d8",
    },
    {
      level: "11",
      bab: "11",
      fort: "7",
      ref: "7",
      will: "3",
      special: "Accelerated evolution",
      adaptive_strike: "2d10",
    },
    {
      level: "12",
      bab: "12",
      fort: "8",
      ref: "8",
      will: "4",
      special: "Evolutionist adaptation, skill boost (+4)",
      adaptive_strike: "2d10",
    },
    {
      level: "13",
      bab: "13",
      fort: "8",
      ref: "8",
      will: "4",
      special: "Evolutionary focus (advanced)",
      adaptive_strike: "3d10",
    },
    {
      level: "14",
      bab: "14",
      fort: "9",
      ref: "9",
      will: "4",
      special: "Evolution drinker, evolutionist adaptation",
      adaptive_strike: "3d10",
    },
    {
      level: "15",
      bab: "15",
      fort: "9",
      ref: "9",
      will: "5",
      special: "Skill boost (+5)",
      adaptive_strike: "4d10",
    },
    {
      level: "16",
      bab: "16",
      fort: "10",
      ref: "10",
      will: "5",
      special: "Evolutionist adaptation",
      adaptive_strike: "4d10",
    },
    {
      level: "17",
      bab: "17",
      fort: "10",
      ref: "10",
      will: "5",
      special: "Flexible skill",
      adaptive_strike: "5d10",
    },
    {
      level: "18",
      bab: "18",
      fort: "11",
      ref: "11",
      will: "6",
      special: "Evolutionist adaptation, skill boost (+6)",
      adaptive_strike: "6d10",
    },
    {
      level: "19",
      bab: "19",
      fort: "11",
      ref: "11",
      will: "6",
      special: "Evolutionary focus (ultimate)",
      adaptive_strike: "7d10",
    },
    {
      level: "20",
      bab: "20",
      fort: "12",
      ref: "12",
      will: "6",
      special: "Evolutionist adaptation, niche ability",
      adaptive_strike: "8d10",
    },
  ],
  Mechanic: [
    {
      level: "1",
      bab: "0",
      fort: "2",
      ref: "2",
      will: "0",
      special: "Artificial intelligence, bypass +1, custom rig",
    },
    {
      level: "2",
      bab: "1",
      fort: "3",
      ref: "3",
      will: "0",
      special: "Mechanic trick",
    },
    {
      level: "3",
      bab: "2",
      fort: "3",
      ref: "3",
      will: "1",
      special: "Overload, weapon specialization",
    },
    {
      level: "4",
      bab: "3",
      fort: "4",
      ref: "4",
      will: "1",
      special: "Mechanic trick",
    },
    {
      level: "5",
      bab: "3",
      fort: "4",
      ref: "4",
      will: "1",
      special: "Bypass +2, remote hack",
    },
    {
      level: "6",
      bab: "4",
      fort: "5",
      ref: "5",
      will: "2",
      special: "Mechanic trick",
    },
    {
      level: "7",
      bab: "5",
      fort: "5",
      ref: "5",
      will: "2",
      special: "Expert rig, miracle worker 1/day",
    },
    {
      level: "8",
      bab: "6",
      fort: "6",
      ref: "6",
      will: "2",
      special: "Mechanic trick",
    },
    {
      level: "9",
      bab: "6",
      fort: "6",
      ref: "6",
      will: "3",
      special: "Bypass +3, override",
    },
    {
      level: "10",
      bab: "7",
      fort: "7",
      ref: "7",
      will: "3",
      special: "Mechanic trick",
    },
    {
      level: "11",
      bab: "8",
      fort: "7",
      ref: "7",
      will: "3",
      special: "Coordinated assault +1, miracle worker 2/day",
    },
    {
      level: "12",
      bab: "9",
      fort: "8",
      ref: "8",
      will: "4",
      special: "Mechanic trick",
    },
    {
      level: "13",
      bab: "9",
      fort: "8",
      ref: "8",
      will: "4",
      special: "Advanced rig, bypass +4",
    },
    {
      level: "14",
      bab: "10",
      fort: "9",
      ref: "9",
      will: "4",
      special: "Mechanic trick",
    },
    {
      level: "15",
      bab: "11",
      fort: "9",
      ref: "9",
      will: "5",
      special: "Miracle worker 3/day",
    },
    {
      level: "16",
      bab: "12",
      fort: "10",
      ref: "10",
      will: "5",
      special: "Mechanic trick",
    },
    {
      level: "17",
      bab: "12",
      fort: "10",
      ref: "10",
      will: "5",
      special: "Bypass +5, control net, coordinated assault 2",
    },
    {
      level: "18",
      bab: "13",
      fort: "11",
      ref: "11",
      will: "6",
      special: "Mechanic trick",
    },
    {
      level: "19",
      bab: "14",
      fort: "11",
      ref: "11",
      will: "6",
      special: "Ghost in the machine, miracle worker 4/day, superior rig",
    },
    {
      level: "20",
      bab: "15",
      fort: "12",
      ref: "12",
      will: "6",
      special: "Bypass +6, mechanic trick, tech master",
    },
  ],
  Mystic: [
    { level: "1", bab: "0", fort: "0", ref: "0", will: "2", special: "Connection, connection power, connection spell, healing touch", spells: { "1st": 2 } },
    { level: "2", bab: "1", fort: "0", ref: "0", will: "3", special: "Channel skill +1, mindlink", spells: { "1st": 2 } },
    { level: "3", bab: "2", fort: "1", ref: "1", will: "3", special: "Connection power, weapon specialization", spells: { "1st": 3 } },
    { level: "4", bab: "3", fort: "1", ref: "1", will: "4", special: "Connection spell", spells: { "1st": 3, "2nd": 2 } },
    { level: "5", bab: "3", fort: "1", ref: "1", will: "4", special: "Channel skill +2", spells: { "1st": 4, "2nd": 2 } },
    { level: "6", bab: "4", fort: "2", ref: "2", will: "5", special: "Connection power", spells: { "1st": 4, "2nd": 3 } },
    { level: "7", bab: "5", fort: "2", ref: "2", will: "5", special: "Connection spell", spells: { "1st": 4, "2nd": 3, "3rd": 2 } },
    { level: "8", bab: "6", fort: "2", ref: "2", will: "6", special: "Channel skill +3", spells: { "1st": 4, "2nd": 4, "3rd": 2 } },
    { level: "9", bab: "6", fort: "3", ref: "3", will: "6", special: "Connection power", spells: { "1st": 5, "2nd": 4, "3rd": 3 } },
    { level: "10", bab: "7", fort: "3", ref: "3", will: "7", special: "Connection spell", spells: { "1st": 5, "2nd": 4, "3rd": 3, "4th": 2 } },
    { level: "11", bab: "8", fort: "3", ref: "3", will: "7", special: "Channel skill +4, telepathic bond", spells: { "1st": 5, "2nd": 4, "3rd": 4, "4th": 2 } },
    { level: "12", bab: "9", fort: "4", ref: "4", will: "8", special: "Connection power", spells: { "1st": 5, "2nd": 5, "3rd": 4, "4th": 3 } },
    { level: "13", bab: "9", fort: "4", ref: "4", will: "8", special: "Connection spell", spells: { "1st": 5, "2nd": 5, "3rd": 4, "4th": 3, "5th": 2 } },
    { level: "14", bab: "10", fort: "4", ref: "4", will: "9", special: "Channel skill +5", spells: { "1st": 5, "2nd": 5, "3rd": 4, "4th": 4, "5th": 2 } },
    { level: "15", bab: "11", fort: "5", ref: "5", will: "9", special: "Connection power", spells: { "1st": 5, "2nd": 5, "3rd": 5, "4th": 4, "5th": 3 } },
    { level: "16", bab: "12", fort: "5", ref: "5", will: "10", special: "Connection spell", spells: { "1st": 5, "2nd": 5, "3rd": 5, "4th": 4, "5th": 3, "6th": 2 } },
    { level: "17", bab: "12", fort: "5", ref: "5", will: "10", special: "Channel skill +6", spells: { "1st": 5, "2nd": 5, "3rd": 5, "4th": 4, "5th": 4, "6th": 2 } },
    { level: "18", bab: "13", fort: "6", ref: "6", will: "11", special: "Connection power", spells: { "1st": 5, "2nd": 5, "3rd": 5, "4th": 5, "5th": 4, "6th": 3 } },
    { level: "19", bab: "14", fort: "6", ref: "6", will: "11", special: "Transcendence", spells: { "1st": 5, "2nd": 5, "3rd": 5, "4th": 5, "5th": 5, "6th": 4 } },
    { level: "20", bab: "15", fort: "6", ref: "6", will: "12", special: "Channel skill +7, enlightenment", spells: { "1st": 5, "2nd": 5, "3rd": 5, "4th": 5, "5th": 5, "6th": 5 } }
]
};

export default classProgressionTable;
