const classProgressionTable = {
  Biohacker: [
    {
      level: "1",
      bab: "0",
      fort: "2",
      ref: "0",
      will: "0",
      special:
        "Biohacks, custom microlab, injection expert, primary field of study, scientific method",
    },
    {
      level: "2",
      bab: "1",
      fort: "3",
      ref: "0",
      will: "0",
      special: "Injection expert +1, theorem",
    },
    {
      level: "3",
      bab: "2",
      fort: "3",
      ref: "1",
      will: "1",
      special: "Spark of ingenuity 1/day, weapon specialization",
    },
    {
      level: "4",
      bab: "3",
      fort: "4",
      ref: "1",
      will: "1",
      special: "Theorem",
    },
    {
      level: "5",
      bab: "3",
      fort: "4",
      ref: "1",
      will: "1",
      special:
        "Custom microlab (advanced medkit), primary field of study breakthrough",
    },
    {
      level: "6",
      bab: "4",
      fort: "5",
      ref: "2",
      will: "2",
      special: "Theorem",
    },
    {
      level: "7",
      bab: "5",
      fort: "5",
      ref: "2",
      will: "2",
      special: "Secondary field of study",
    },
    {
      level: "8",
      bab: "6",
      fort: "6",
      ref: "2",
      will: "2",
      special: "Theorem",
    },
    {
      level: "9",
      bab: "6",
      fort: "6",
      ref: "3",
      will: "3",
      special:
        "Custom microlab (medical lab, 90 feet), injection expert +2, spark of ingenuity 2/day",
    },
    {
      level: "10",
      bab: "7",
      fort: "7",
      ref: "3",
      will: "3",
      special: "Theorem",
    },
    {
      level: "11",
      bab: "8",
      fort: "7",
      ref: "3",
      will: "3",
      special: "Secondary field of study breakthrough",
    },
    {
      level: "12",
      bab: "9",
      fort: "8",
      ref: "4",
      will: "4",
      special: "Theorem",
    },
    {
      level: "13",
      bab: "9",
      fort: "8",
      ref: "4",
      will: "4",
      special: "Tertiary field of study",
    },
    {
      level: "14",
      bab: "10",
      fort: "9",
      ref: "4",
      will: "4",
      special: "Theorem",
    },
    {
      level: "15",
      bab: "11",
      fort: "9",
      ref: "5",
      will: "5",
      special: "Spark of ingenuity 3/day",
    },
    {
      level: "16",
      bab: "12",
      fort: "10",
      ref: "5",
      will: "5",
      special: "Theorem",
    },
    {
      level: "17",
      bab: "12",
      fort: "10",
      ref: "5",
      will: "5",
      special:
        "Custom microlab (120 feet), tertiary field of study breakthrough",
    },
    {
      level: "18",
      bab: "13",
      fort: "11",
      ref: "6",
      will: "6",
      special: "Injection expert +3, theorem",
    },
    {
      level: "19",
      bab: "14",
      fort: "11",
      ref: "6",
      will: "6",
      special: "Resolve analysis",
    },
    {
      level: "20",
      bab: "15",
      fort: "12",
      ref: "6",
      will: "6",
      special: "Superserum, theorem",
    },
  ],
  Envoy: [
    {
      level: "1",
      bab: "0",
      fort: "0",
      ref: "2",
      will: "2",
      special: "Envoy improvisation, expertise (1d6), skill expertise",
    },
    {
      level: "2",
      bab: "1",
      fort: "0",
      ref: "3",
      will: "3",
      special: "Envoy improvisation",
    },
    {
      level: "3",
      bab: "2",
      fort: "1",
      ref: "3",
      will: "3",
      special: "Expertise talent, weapon specialization",
    },
    {
      level: "4",
      bab: "3",
      fort: "1",
      ref: "4",
      will: "4",
      special: "Envoy improvisation",
    },
    {
      level: "5",
      bab: "3",
      fort: "1",
      ref: "4",
      will: "4",
      special: "Expertise (1d6+1), skill expertise",
    },
    {
      level: "6",
      bab: "4",
      fort: "2",
      ref: "5",
      will: "5",
      special: "Envoy improvisation",
    },
    {
      level: "7",
      bab: "5",
      fort: "2",
      ref: "5",
      will: "5",
      special: "Expertise talent",
    },
    {
      level: "8",
      bab: "6",
      fort: "2",
      ref: "6",
      will: "6",
      special: "Envoy improvisation",
    },
    {
      level: "9",
      bab: "6",
      fort: "3",
      ref: "6",
      will: "6",
      special: "Expertise (1d6+2), skill expertise",
    },
    {
      level: "10",
      bab: "7",
      fort: "3",
      ref: "7",
      will: "7",
      special: "Envoy improvisation",
    },
    {
      level: "11",
      bab: "8",
      fort: "3",
      ref: "7",
      will: "7",
      special: "Expertise talent",
    },
    {
      level: "12",
      bab: "9",
      fort: "4",
      ref: "8",
      will: "8",
      special: "Envoy improvisation",
    },
    {
      level: "13",
      bab: "9",
      fort: "4",
      ref: "8",
      will: "8",
      special: "Expertise (1d8+2), skill expertise",
    },
    {
      level: "14",
      bab: "10",
      fort: "4",
      ref: "9",
      will: "9",
      special: "Envoy improvisation",
    },
    {
      level: "15",
      bab: "11",
      fort: "5",
      ref: "9",
      will: "9",
      special: "Expertise talent",
    },
    {
      level: "16",
      bab: "12",
      fort: "5",
      ref: "10",
      will: "10",
      special: "Envoy improvisation",
    },
    {
      level: "17",
      bab: "12",
      fort: "5",
      ref: "10",
      will: "10",
      special: "Expertise (1d8+3), skill expertise",
    },
    {
      level: "18",
      bab: "13",
      fort: "6",
      ref: "11",
      will: "11",
      special: "Envoy improvisation",
    },
    {
      level: "19",
      bab: "14",
      fort: "6",
      ref: "11",
      will: "11",
      special: "Expertise talent",
    },
    {
      level: "20",
      bab: "15",
      fort: "6",
      ref: "12",
      will: "12",
      special: "Envoy improvisation, expertise (1d8+4), true expertise",
    },
  ],
  Evolutionist: [
    {
      level: "1",
      bab: "1",
      fort: "2",
      ref: "2",
      will: "0",
      special:
        "Adaptive strike, evolution track, flexible skill, niche, niche ability",
      adaptive_strike: "1d6",
    },
    {
      level: "2",
      bab: "2",
      fort: "3",
      ref: "3",
      will: "0",
      special: "Augmented form, evolutionist adaptation, fulcrum",
      adaptive_strike: "1d6",
    },
    {
      level: "3",
      bab: "3",
      fort: "3",
      ref: "3",
      will: "1",
      special: "Skill boost (+1), weapon specialization",
      adaptive_strike: "1d6",
    },
    {
      level: "4",
      bab: "4",
      fort: "4",
      ref: "4",
      will: "1",
      special: "Evolutionist adaptation",
      adaptive_strike: "1d6",
    },
    {
      level: "5",
      bab: "5",
      fort: "4",
      ref: "4",
      will: "1",
      special: "Evolution drain",
      adaptive_strike: "1d6",
    },
    {
      level: "6",
      bab: "6",
      fort: "5",
      ref: "5",
      will: "2",
      special: "Evolutionist adaptation, skill boost (+2)",
      adaptive_strike: "1d10",
    },
    {
      level: "7",
      bab: "7",
      fort: "5",
      ref: "5",
      will: "2",
      special: "Evolutionary focus (basic)",
      adaptive_strike: "1d10",
    },
    {
      level: "8",
      bab: "8",
      fort: "6",
      ref: "6",
      will: "2",
      special: "Evolutionist adaptation",
      adaptive_strike: "1d10",
    },
    {
      level: "9",
      bab: "9",
      fort: "6",
      ref: "6",
      will: "3",
      special: "Flexible skill, skill boost (+3)",
      adaptive_strike: "2d8",
    },
    {
      level: "10",
      bab: "10",
      fort: "7",
      ref: "7",
      will: "3",
      special: "Evolutionist adaptation, niche ability",
      adaptive_strike: "2d8",
    },
    {
      level: "11",
      bab: "11",
      fort: "7",
      ref: "7",
      will: "3",
      special: "Accelerated evolution",
      adaptive_strike: "2d10",
    },
    {
      level: "12",
      bab: "12",
      fort: "8",
      ref: "8",
      will: "4",
      special: "Evolutionist adaptation, skill boost (+4)",
      adaptive_strike: "2d10",
    },
    {
      level: "13",
      bab: "13",
      fort: "8",
      ref: "8",
      will: "4",
      special: "Evolutionary focus (advanced)",
      adaptive_strike: "3d10",
    },
    {
      level: "14",
      bab: "14",
      fort: "9",
      ref: "9",
      will: "4",
      special: "Evolution drinker, evolutionist adaptation",
      adaptive_strike: "3d10",
    },
    {
      level: "15",
      bab: "15",
      fort: "9",
      ref: "9",
      will: "5",
      special: "Skill boost (+5)",
      adaptive_strike: "4d10",
    },
    {
      level: "16",
      bab: "16",
      fort: "10",
      ref: "10",
      will: "5",
      special: "Evolutionist adaptation",
      adaptive_strike: "4d10",
    },
    {
      level: "17",
      bab: "17",
      fort: "10",
      ref: "10",
      will: "5",
      special: "Flexible skill",
      adaptive_strike: "5d10",
    },
    {
      level: "18",
      bab: "18",
      fort: "11",
      ref: "11",
      will: "6",
      special: "Evolutionist adaptation, skill boost (+6)",
      adaptive_strike: "6d10",
    },
    {
      level: "19",
      bab: "19",
      fort: "11",
      ref: "11",
      will: "6",
      special: "Evolutionary focus (ultimate)",
      adaptive_strike: "7d10",
    },
    {
      level: "20",
      bab: "20",
      fort: "12",
      ref: "12",
      will: "6",
      special: "Evolutionist adaptation, niche ability",
      adaptive_strike: "8d10",
    },
  ],
  Mechanic: [
    {
      level: "1",
      bab: "0",
      fort: "2",
      ref: "2",
      will: "0",
      special: "Artificial intelligence, bypass +1, custom rig",
    },
    {
      level: "2",
      bab: "1",
      fort: "3",
      ref: "3",
      will: "0",
      special: "Mechanic trick",
    },
    {
      level: "3",
      bab: "2",
      fort: "3",
      ref: "3",
      will: "1",
      special: "Overload, weapon specialization",
    },
    {
      level: "4",
      bab: "3",
      fort: "4",
      ref: "4",
      will: "1",
      special: "Mechanic trick",
    },
    {
      level: "5",
      bab: "3",
      fort: "4",
      ref: "4",
      will: "1",
      special: "Bypass +2, remote hack",
    },
    {
      level: "6",
      bab: "4",
      fort: "5",
      ref: "5",
      will: "2",
      special: "Mechanic trick",
    },
    {
      level: "7",
      bab: "5",
      fort: "5",
      ref: "5",
      will: "2",
      special: "Expert rig, miracle worker 1/day",
    },
    {
      level: "8",
      bab: "6",
      fort: "6",
      ref: "6",
      will: "2",
      special: "Mechanic trick",
    },
    {
      level: "9",
      bab: "6",
      fort: "6",
      ref: "6",
      will: "3",
      special: "Bypass +3, override",
    },
    {
      level: "10",
      bab: "7",
      fort: "7",
      ref: "7",
      will: "3",
      special: "Mechanic trick",
    },
    {
      level: "11",
      bab: "8",
      fort: "7",
      ref: "7",
      will: "3",
      special: "Coordinated assault +1, miracle worker 2/day",
    },
    {
      level: "12",
      bab: "9",
      fort: "8",
      ref: "8",
      will: "4",
      special: "Mechanic trick",
    },
    {
      level: "13",
      bab: "9",
      fort: "8",
      ref: "8",
      will: "4",
      special: "Advanced rig, bypass +4",
    },
    {
      level: "14",
      bab: "10",
      fort: "9",
      ref: "9",
      will: "4",
      special: "Mechanic trick",
    },
    {
      level: "15",
      bab: "11",
      fort: "9",
      ref: "9",
      will: "5",
      special: "Miracle worker 3/day",
    },
    {
      level: "16",
      bab: "12",
      fort: "10",
      ref: "10",
      will: "5",
      special: "Mechanic trick",
    },
    {
      level: "17",
      bab: "12",
      fort: "10",
      ref: "10",
      will: "5",
      special: "Bypass +5, control net, coordinated assault 2",
    },
    {
      level: "18",
      bab: "13",
      fort: "11",
      ref: "11",
      will: "6",
      special: "Mechanic trick",
    },
    {
      level: "19",
      bab: "14",
      fort: "11",
      ref: "11",
      will: "6",
      special: "Ghost in the machine, miracle worker 4/day, superior rig",
    },
    {
      level: "20",
      bab: "15",
      fort: "12",
      ref: "12",
      will: "6",
      special: "Bypass +6, mechanic trick, tech master",
    },
  ],
  Mystic: [
    { level: "1", bab: "0", fort: "0", ref: "0", will: "2", special: "Connection, connection power, connection spell, healing touch", spells: [2, "-", "-", "-", "-", "-"] },
    { level: "2", bab: "1", fort: "0", ref: "0", will: "3", special: "Channel skill +1, mindlink", spells: [2, "-", "-", "-", "-", "-"] },
    { level: "3", bab: "2", fort: "1", ref: "1", will: "3", special: "Connection power, weapon specialization", spells: [3, "-", "-", "-", "-", "-"] },
    { level: "4", bab: "3", fort: "1", ref: "1", will: "4", special: "Connection spell", spells: [3, 2, "-", "-", "-", "-"] },
    { level: "5", bab: "3", fort: "1", ref: "1", will: "4", special: "Channel skill +2", spells: [4, 2, "-", "-", "-", "-"] },
    { level: "6", bab: "4", fort: "2", ref: "2", will: "5", special: "Connection power", spells: [4, 3, "-", "-", "-", "-"] },
    { level: "7", bab: "5", fort: "2", ref: "2", will: "5", special: "Connection spell", spells: [4, 3, 2, "-", "-", "-"] },
    { level: "8", bab: "6", fort: "2", ref: "2", will: "6", special: "Channel skill +3", spells: [4, 4, 2, "-", "-", "-"]},
    { level: "9", bab: "6", fort: "3", ref: "3", will: "6", special: "Connection power", spells: [5, 4, 3, "-", "-", "-"] },
    { level: "10", bab: "7", fort: "3", ref: "3", will: "7", special: "Connection spell", spells: [5, 4, 3, 2, "-", "-"] },
    { level: "11", bab: "8", fort: "3", ref: "3", will: "7", special: "Channel skill +4, telepathic bond", spells: [5, 4, 4, 2, "-", "-"] },
    { level: "12", bab: "9", fort: "4", ref: "4", will: "8", special: "Connection power", spells:[5, 5, 4, 3, "-", "-"] },
    { level: "13", bab: "9", fort: "4", ref: "4", will: "8", special: "Connection spell", spells:[5, 5, 4, 3, 2, "-"] },
    { level: "14", bab: "10", fort: "4", ref: "4", will: "9", special: "Channel skill +5", spells: [5, 5, 4, 4, 2, "-"]  },
    { level: "15", bab: "11", fort: "5", ref: "5", will: "9", special: "Connection power", spells: [5, 5, 5, 4, 3, "-"]  },
    { level: "16", bab: "12", fort: "5", ref: "5", will: "10", special: "Connection spell", spells: [5, 5, 5, 4, 3, 2]  },
    { level: "17", bab: "12", fort: "5", ref: "5", will: "10", special: "Channel skill +6", spells: [5, 5, 5, 4, 4, 2] },
    { level: "18", bab: "13", fort: "6", ref: "6", will: "11", special: "Connection power", spells: [5, 5, 5, 5, 4, 3] },
    { level: "19", bab: "14", fort: "6", ref: "6", will: "11", special: "Transcendence", spells: [5, 5, 5, 5, 5, 4] },
    { level: "20", bab: "15", fort: "6", ref: "6", will: "12", special: "Channel skill +7, enlightenment", spells: [5, 5, 5, 5, 5, 5] }
],
Nanocyte: [
    { level: 1, bab: 1, fort: 2, ref: 0, will: 0, special: "Nanite array, nanite surge, primary nanite faculty, primary faculty technique", majorForms: 2, minorForms: 3 },
    { level: 2, bab: 2, fort: 3, ref: 0, will: 0, special: "Defensive dispersal, nanocyte knack", majorForms: 2, minorForms: 4 },
    { level: 3, bab: 3, fort: 3, ref: 1, will: 1, special: "Cyto-conversion (+1), weapon specialization", majorForms: 3, minorForms: 4 },
    { level: 4, bab: 4, fort: 4, ref: 1, will: 1, special: "Nanocyte knack", majorForms: 3, minorForms: 5 },
    { level: 5, bab: 5, fort: 4, ref: 1, will: 1, special: "Primary faculty technique", majorForms: 4, minorForms: 5 },
    { level: 6, bab: 6, fort: 5, ref: 2, will: 2, special: "Nanocyte knack", majorForms: 4, minorForms: 6 },
    { level: 7, bab: 7, fort: 5, ref: 2, will: 2, special: "Manifold array (two arrays)", majorForms: 4, minorForms: 6 },
    { level: 8, bab: 8, fort: 6, ref: 2, will: 2, special: "Nanocyte knack", majorForms: 4, minorForms: 7 },
    { level: 9, bab: 9, fort: 6, ref: 3, will: 3, special: "Primary faculty technique, secondary nanite faculty, secondary faculty technique", majorForms: 5, minorForms: 7 },
    { level: 10, bab: 10, fort: 7, ref: 3, will: 3, special: "Cyto-conversion (+2), nanocyte knack", majorForms: 5, minorForms: 8 },
    { level: 11, bab: 11, fort: 7, ref: 3, will: 3, special: "Eternal nanites", majorForms: 5, minorForms: 8 },
    { level: 12, bab: 12, fort: 8, ref: 4, will: 4, special: "Nanocyte knack", majorForms: 5, minorForms: 9 },
    { level: 13, bab: 13, fort: 8, ref: 4, will: 4, special: "Primary faculty technique, secondary faculty technique", majorForms: 6, minorForms: 9 },
    { level: 14, bab: 14, fort: 9, ref: 4, will: 4, special: "Nanocyte knack", majorForms: 6, minorForms: 10 },
    { level: 15, bab: 15, fort: 9, ref: 5, will: 5, special: "Manifold array (three arrays)", majorForms: 6, minorForms: 10 },
    { level: 16, bab: 16, fort: 10, ref: 5, will: 5, special: "Cyto-conversion (+3), nanocyte knack", majorForms: 6, minorForms: 11 },
    { level: 17, bab: 17, fort: 10, ref: 5, will: 5, special: "Primary faculty technique, secondary faculty technique", majorForms: 7, minorForms: 11 },
    { level: 18, bab: 18, fort: 11, ref: 6, will: 6, special: "Nanocyte knack", majorForms: 7, minorForms: 12 },
    { level: 19, bab: 19, fort: 11, ref: 6, will: 6, special: "Living legion", majorForms: 7, minorForms: 12 },
    { level: 20, bab: 20, fort: 12, ref: 6, will: 6, special: "Infinite array, nanocyte knack", majorForms: 7, minorForms: 13 }
],
Operative: [
    { level: 1, bab: 0, fort: 0, ref: 2, will: 2, special: "Operative’s edge +1, specialization, trick attack +1d4" },
    { level: 2, bab: 1, fort: 0, ref: 3, will: 3, special: "Evasion, operative exploit" },
    { level: 3, bab: 2, fort: 1, ref: 3, will: 3, special: "Operative’s edge +2, quick movement (+10 ft.), trick attack +1d8, weapon specialization" },
    { level: 4, bab: 3, fort: 1, ref: 4, will: 4, special: "Debilitating trick, operative exploit" },
    { level: 5, bab: 3, fort: 1, ref: 4, will: 4, special: "Specialization exploit, trick attack +3d8" },
    { level: 6, bab: 4, fort: 2, ref: 5, will: 5, special: "Operative exploit" },
    { level: 7, bab: 5, fort: 2, ref: 5, will: 5, special: "Operative’s edge +3, specialization skill mastery, trick attack +4d8, uncanny agility" },
    { level: 8, bab: 6, fort: 2, ref: 6, will: 6, special: "Operative exploit, triple attack" },
    { level: 9, bab: 6, fort: 3, ref: 6, will: 6, special: "Quick movement (+20 ft.), trick attack +5d8" },
    { level: 10, bab: 7, fort: 3, ref: 7, will: 7, special: "Operative exploit" },
    { level: 11, bab: 8, fort: 3, ref: 7, will: 7, special: "Operative’s edge +4, specialization power, trick attack +6d8" },
    { level: 12, bab: 9, fort: 4, ref: 8, will: 8, special: "Operative exploit" },
    { level: 13, bab: 9, fort: 4, ref: 8, will: 8, special: "Quad attack, trick attack +7d8" },
    { level: 14, bab: 10, fort: 4, ref: 9, will: 9, special: "Operative exploit" },
    { level: 15, bab: 11, fort: 5, ref: 9, will: 9, special: "Operative’s edge +5, quick movement (+30 ft.), trick attack +8d8" },
    { level: 16, bab: 12, fort: 5, ref: 10, will: 10, special: "Operative exploit" },
    { level: 17, bab: 12, fort: 5, ref: 10, will: 10, special: "Double debilitation, trick attack +9d8" },
    { level: 18, bab: 13, fort: 6, ref: 11, will: 11, special: "Operative exploit" },
    { level: 19, bab: 14, fort: 6, ref: 11, will: 11, special: "Operative’s edge +6, trick attack +10d8" },
    { level: 20, bab: 15, fort: 6, ref: 12, will: 12, special: "Operative exploit, supreme operative" }
],
Precog: [
    { level: 1, bab: 0, fort: 0, ref: 2, will: 0, special: "Anchor, focal paradox, paradox", spells: [2,0,0,0,0,0] },
    { level: 2, bab: 1, fort: 0, ref: 3, will: 0, special: "Temporal anomaly", spells: [2,0,0,0,0,0] },
    { level: 3, bab: 2, fort: 1, ref: 3, will: 1, special: "Chronomatic defense +2, weapon specialization", spells: [3,0,0,0,0,0] },
    { level: 4, bab: 3, fort: 1, ref: 4, will: 1, special: "Temporal aggression", spells: [3,2,0,0,0,0] },
    { level: 5, bab: 3, fort: 1, ref: 4, will: 1, special: "Temporal anomaly", spells: [4,2,0,0,0,0] },
    { level: 6, bab: 4, fort: 2, ref: 5, will: 2, special: "Temporal aggression (allies)", spells: [4,3,0,0,0,0] },
    { level: 7, bab: 5, fort: 2, ref: 5, will: 2, special: "Chronomatic defense +3", spells: [4,3,2,0,0,0] },
    { level: 8, bab: 6, fort: 2, ref: 6, will: 2, special: "Temporal anomaly", spells: [4,4,2,0,0,0] },
    { level: 9, bab: 6, fort: 3, ref: 6, will: 3, special: "Improved anchor", spells: [5,4,3,0,0,0] },
    { level: 10, bab: 7, fort: 3, ref: 7, will: 3, special: "Paradoxical acceleration", spells: [5,4,3,2,0,0] },
    { level: 11, bab: 8, fort: 3, ref: 7, will: 3, special: "Temporal anomaly", spells: [5,4,4,2,0,0] },
    { level: 12, bab: 9, fort: 4, ref: 8, will: 4, special: "Chronomatic flow +1", spells: [5,5,4,3,0,0] },
    { level: 13, bab: 9, fort: 4, ref: 8, will: 4, special: "Chronomatic defense +4", spells: [5,5,4,3,2,0] },
    { level: 14, bab: 10, fort: 4, ref: 9, will: 4, special: "Temporal anomaly", spells: [5,5,4,4,2,0] },
    { level: 15, bab: 11, fort: 5, ref: 9, will: 5, special: "Greater anchor", spells: [5,5,5,4,3,0] },
    { level: 16, bab: 12, fort: 5, ref: 10, will: 5, special: "Chronomatic flow +2", spells: [5,5,5,4,3,2] },
    { level: 17, bab: 12, fort: 5, ref: 10, will: 5, special: "Temporal anomaly", spells: [5,5,5,4,4,2] },
    { level: 18, bab: 13, fort: 6, ref: 11, will: 6, special: "Chronomatic defense +5", spells: [5,5,5,5,4,3] },
    { level: 19, bab: 14, fort: 6, ref: 11, will: 6, special: "Chronomatic flow +3", spells: [5,5,5,5,5,4] },
    { level: 20, bab: 15, fort: 6, ref: 12, will: 6, special: "Temporal anomaly, timeless paragon", spells: [5,5,5,5,5,5] }
],
Solarian: [
    { level: 1, bab: 0, fort: 2, ref: 0, will: 2, special: "Skill adept, solar manifestation, stellar mode, stellar revelation (black hole, supernova)", solarArmor: "1 AC", solarFlare: "1d4", solarShield: "1/2", solarWeapon: "1d6" },
    { level: 2, bab: 1, fort: 3, ref: 0, will: 3, special: "Stellar revelation", solarArmor: "1 AC", solarFlare: "1d4", solarShield: "1/2", solarWeapon: "1d6" },
    { level: 3, bab: 2, fort: 3, ref: 1, will: 3, special: "Sidereal influence (2 skills), weapon specialization", solarArmor: "1 AC", solarFlare: "1d4", solarShield: "1/2", solarWeapon: "1d6" },
    { level: 4, bab: 3, fort: 4, ref: 1, will: 4, special: "Stellar revelation", solarArmor: "1 AC", solarFlare: "1d4", solarShield: "1/2", solarWeapon: "1d6" },
    { level: 5, bab: 3, fort: 4, ref: 1, will: 4, special: "Specialization exploit", solarArmor: "1 AC, resistance 5", solarFlare: "1d4", solarShield: "1/3", solarWeapon: "1d6" },
    { level: 6, bab: 4, fort: 5, ref: 2, will: 5, special: "Stellar revelation", solarArmor: "1 AC, resistance 5", solarFlare: "2d4", solarShield: "1/3", solarWeapon: "2d6" },
    { level: 7, bab: 5, fort: 5, ref: 2, will: 5, special: "Flashing strikes", solarArmor: "1 AC, resistance 5", solarFlare: "2d4", solarShield: "1/3", solarWeapon: "2d6" },
    { level: 8, bab: 6, fort: 6, ref: 2, will: 6, special: "Stellar revelation", solarArmor: "1 AC, resistance 5", solarFlare: "2d4", solarShield: "1/3", solarWeapon: "2d6" },
    { level: 9, bab: 6, fort: 6, ref: 3, will: 6, special: "Zenith revelations", solarArmor: "1 AC, resistance 5", solarFlare: "3d4", solarShield: "1/3", solarWeapon: "3d6" },
    { level: 10, bab: 7, fort: 7, ref: 3, will: 7, special: "Stellar revelation", solarArmor: "2 AC, resistance 10", solarFlare: "3d4", solarShield: "1/4", solarWeapon: "3d6" },
    { level: 11, bab: 8, fort: 7, ref: 3, will: 7, special: "Sidereal influence (4 skills)", solarArmor: "2 AC, resistance 10", solarFlare: "3d4", solarShield: "1/4", solarWeapon: "3d6" },
    { level: 12, bab: 9, fort: 8, ref: 4, will: 8, special: "Stellar revelation", solarArmor: "2 AC, resistance 10", solarFlare: "4d4", solarShield: "1/4", solarWeapon: "4d6" },
    { level: 13, bab: 9, fort: 8, ref: 4, will: 8, special: "Solarian’s onslaught", solarArmor: "2 AC, resistance 10", solarFlare: "5d4", solarShield: "1/4", solarWeapon: "5d6" },
    { level: 14, bab: 10, fort: 9, ref: 4, will: 9, special: "Stellar revelation", solarArmor: "2 AC, resistance 10", solarFlare: "6d4", solarShield: "1/4", solarWeapon: "6d6" },
    { level: 15, bab: 11, fort: 9, ref: 5, will: 9, special: "Greater anchor", solarArmor: "2 AC, resistance 15", solarFlare: "7d4", solarShield: "1/5", solarWeapon: "7d6" },
    { level: 16, bab: 12, fort: 10, ref: 5, will: 10, special: "Stellar revelation", solarArmor: "2 AC, resistance 15", solarFlare: "8d4", solarShield: "1/5", solarWeapon: "8d6" },
    { level: 17, bab: 12, fort: 10, ref: 5, will: 10, special: "Zenith revelations", solarArmor: "2 AC, resistance 15", solarFlare: "9d4", solarShield: "1/5", solarWeapon: "9d6" },
    { level: 18, bab: 13, fort: 11, ref: 6, will: 11, special: "Stellar revelation", solarArmor: "2 AC, resistance 15", solarFlare: "10d4", solarShield: "1/5", solarWeapon: "10d6" },
    { level: 19, bab: 14, fort: 11, ref: 6, will: 11, special: "Sidereal influence (6 skills)", solarArmor: "2 AC, resistance 15", solarFlare: "11d4", solarShield: "1/5", solarWeapon: "11d6" },
    { level: 20, bab: 15, fort: 12, ref: 6, will: 12, special: "Stellar paragon, stellar revelation", solarArmor: "2 AC, resistance 20", solarFlare: "12d4", solarShield: "1/6", solarWeapon: "12d6" }
],
Soldier: [
    { level: 1, bab: 1, fort: 2, ref: 0, will: 2, special: "Primary fighting style, primary style technique" },
    { level: 2, bab: 2, fort: 3, ref: 0, will: 3, special: "Combat feat" },
    { level: 3, bab: 3, fort: 3, ref: 1, will: 3, special: "Gear boost, weapon specialization" },
    { level: 4, bab: 4, fort: 4, ref: 1, will: 4, special: "Combat feat" },
    { level: 5, bab: 5, fort: 4, ref: 1, will: 4, special: "Primary style technique" },
    { level: 6, bab: 6, fort: 5, ref: 2, will: 5, special: "Combat feat" },
    { level: 7, bab: 7, fort: 5, ref: 2, will: 5, special: "Gear boost" },
    { level: 8, bab: 8, fort: 6, ref: 2, will: 6, special: "Combat feat" },
    { level: 9, bab: 9, fort: 6, ref: 3, will: 6, special: "Primary style technique, secondary fighting style, secondary style technique" },
    { level: 10, bab: 10, fort: 7, ref: 3, will: 7, special: "Combat feat" },
    { level: 11, bab: 11, fort: 7, ref: 3, will: 7, special: "Gear boost, soldier’s onslaught" },
    { level: 12, bab: 12, fort: 8, ref: 4, will: 8, special: "Combat feat" },
    { level: 13, bab: 13, fort: 8, ref: 4, will: 8, special: "Primary style technique, secondary style technique" },
    { level: 14, bab: 14, fort: 9, ref: 4, will: 9, special: "Combat feat" },
    { level: 15, bab: 15, fort: 9, ref: 5, will: 9, special: "Gear boost" },
    { level: 16, bab: 16, fort: 10, ref: 5, will: 10, special: "Combat feat" },
    { level: 17, bab: 17, fort: 10, ref: 5, will: 10, special: "Primary style technique, secondary style technique" },
    { level: 18, bab: 18, fort: 11, ref: 6, will: 11, special: "Combat feat" },
    { level: 19, bab: 19, fort: 11, ref: 6, will: 11, special: "Gear boost" },
    { level: 20, bab: 20, fort: 12, ref: 6, will: 12, special: "Combat feat, kill shot" }
],
Technomancer: [
    { level: 1, bab: 0, fort: 0, ref: 0, will: 2, special: "Spell cache", spells: [2, '-', '-', '-', '-', '-'] },
    { level: 2, bab: 1, fort: 0, ref: 0, will: 3, special: "Magic hack", spells: [2, '-', '-', '-', '-', '-'] },
    { level: 3, bab: 2, fort: 1, ref: 1, will: 3, special: "Spell Focus, techlore +1, weapon specialization", spells: [3, '-', '-', '-', '-', '-'] },
    { level: 4, bab: 3, fort: 1, ref: 1, will: 4, special: "", spells: [3, 2, '-', '-', '-', '-'] },
    { level: 5, bab: 3, fort: 1, ref: 1, will: 4, special: "Magic hack", spells: [4, 2, '-', '-', '-', '-'] },
    { level: 6, bab: 4, fort: 2, ref: 2, will: 5, special: "Cache capacitor 1, techlore +2", spells: [4, 3, '-', '-', '-', '-'] },
    { level: 7, bab: 5, fort: 2, ref: 2, will: 5, special: "", spells: [4, 3, 2, '-', '-', '-'] },
    { level: 8, bab: 6, fort: 2, ref: 2, will: 6, special: "Magic hack", spells: [4, 4, 2, '-', '-', '-'] },
    { level: 9, bab: 6, fort: 3, ref: 3, will: 6, special: "Techlore +3", spells: [5, 4, 3, '-', '-', '-'] },
    { level: 10, bab: 7, fort: 3, ref: 3, will: 7, special: "", spells: [5, 4, 3, 2, '-', '-'] },
    { level: 11, bab: 8, fort: 3, ref: 3, will: 7, special: "Magic hack", spells: [5, 4, 4, 2, '-', '-'] },
    { level: 12, bab: 9, fort: 4, ref: 4, will: 8, special: "Cache capacitor 2, techlore +4", spells: [5, 5, 4, 3, '-', '-'] },
    { level: 13, bab: 9, fort: 4, ref: 4, will: 8, special: "", spells: [5, 5, 4, 3, 2, '-'] },
    { level: 14, bab: 10, fort: 4, ref: 4, will: 9, special: "Magic hack", spells: [5, 5, 4, 4, 2, '-'] },
    { level: 15, bab: 11, fort: 5, ref: 5, will: 9, special: "Techlore +5", spells: [5, 5, 5, 4, 3, '-'] },
    { level: 16, bab: 12, fort: 5, ref: 5, will: 10, special: "", spells: [5, 5, 5, 4, 3, 2] },
    { level: 17, bab: 12, fort: 5, ref: 5, will: 10, special: "Magic hack", spells: [5, 5, 5, 4, 4, 2] },
    { level: 18, bab: 13, fort: 6, ref: 6, will: 11, special: "Cache capacitor 3, techlore +6", spells: [5, 5, 5, 5, 4, 3] },
    { level: 19, bab: 14, fort: 6, ref: 6, will: 11, special: "Resolve attunement", spells: [5, 5, 5, 5, 5, 4] },
    { level: 20, bab: 15, fort: 6, ref: 6, will: 12, special: "Fuse spells, magic hack", spells: [5, 5, 5, 5, 5, 5] }
],
Vanguard: [
    { level: 1, bab: 1, fort: 2, ref: 2, will: 0, special: "Entropic pool, entropic strike, first vanguard aspect (aspect insight)", esd: "1d3" },
    { level: 2, bab: 2, fort: 3, ref: 3, will: 0, special: "Mitigate, vanguard discipline", esd: "1d3" },
    { level: 3, bab: 3, fort: 3, ref: 3, will: 1, special: "Reactive 1/day, weapon specialization", esd: "1d4" },
    { level: 4, bab: 4, fort: 4, ref: 4, will: 1, special: "First vanguard aspect (aspect embodiment), vanguard discipline", esd: "1d4" },
    { level: 5, bab: 5, fort: 4, ref: 4, will: 1, special: "Entropic attunement (weapon special property)", esd: "1d6" },
    { level: 6, bab: 6, fort: 5, ref: 5, will: 2, special: "Vanguard discipline", esd: "2d6" },
    { level: 7, bab: 7, fort: 5, ref: 5, will: 2, special: "Entropic attunement (critical hit effect), uncanny agility", esd: "2d6" },
    { level: 8, bab: 8, fort: 6, ref: 6, will: 2, special: "Second vanguard aspect (second aspect insight), vanguard discipline", esd: "2d6" },
    { level: 9, bab: 9, fort: 6, ref: 6, will: 3, special: "Reactive 2/day", esd: "3d6" },
    { level: 10, bab: 10, fort: 7, ref: 7, will: 3, special: "Entropic attunement (reach), vanguard discipline", esd: "3d6" },
    { level: 11, bab: 11, fort: 7, ref: 7, will: 3, special: "Flashing strikes", esd: "3d6" },
    { level: 12, bab: 12, fort: 8, ref: 8, will: 4, special: "First vanguard aspect (aspect catalyst), vanguard discipline", esd: "4d6" },
    { level: 13, bab: 13, fort: 8, ref: 8, will: 4, special: "Entropic attunement (blast)", esd: "5d6" },
    { level: 14, bab: 14, fort: 9, ref: 9, will: 4, special: "Vanguard discipline", esd: "6d6" },
    { level: 15, bab: 15, fort: 9, ref: 9, will: 5, special: "Reactive 3/day, uncanny speed", esd: "7d6" },
    { level: 16, bab: 16, fort: 10, ref: 10, will: 5, special: "Entropic attunement (radius), vanguard discipline", esd: "8d6" },
    { level: 17, bab: 17, fort: 10, ref: 10, will: 5, special: "Second vanguard aspect (second aspect embodiment)", esd: "9d6" },
    { level: 18, bab: 18, fort: 11, ref: 11, will: 6, special: "First vanguard aspect (aspect finale), vanguard discipline", esd: "10d6" },
    { level: 19, bab: 19, fort: 11, ref: 11, will: 6, special: "Agent of change, entropic attunement (severe wound)", esd: "11d6" },
    { level: 20, bab: 20, fort: 12, ref: 12, will: 6, special: "Invulnerability, vanguard discipline", esd: "12d6" }
],
Witchwarper: [
    { level: 1, bab: 0, fort: 0, ref: 2, will: 0, special: "Infinite worlds (1st-level spells)", spells: [2, "-", "-", "-", "-", "-"] },
    { level: 2, bab: 1, fort: 0, ref: 3, will: 0, special: "Paradigm shift", spells: [2, "-", "-", "-", "-", "-"] },
    { level: 3, bab: 2, fort: 1, ref: 3, will: 1, special: "Compound sight +1, weapon specialization", spells: [3, "-", "-", "-", "-", "-"] },
    { level: 4, bab: 3, fort: 1, ref: 4, will: 1, special: "Infinite worlds (2nd-level spells)", spells: [3, 2, "-", "-", "-", "-"] },
    { level: 5, bab: 3, fort: 1, ref: 4, will: 1, special: "Paradigm shift", spells: [4, 2, "-", "-", "-", "-"] },
    { level: 6, bab: 4, fort: 2, ref: 5, will: 2, special: "Alternate outcome 1/day, compound sight +2", spells: [4, 3, "-", "-", "-", "-"] },
    { level: 7, bab: 5, fort: 2, ref: 5, will: 2, special: "Infinite worlds (3rd-level spells)", spells: [4, 3, 2, "-", "-", "-"] },
    { level: 8, bab: 6, fort: 2, ref: 6, will: 2, special: "Paradigm shift", spells: [4, 4, 2, "-", "-", "-"] },
    { level: 9, bab: 6, fort: 3, ref: 6, will: 3, special: "Compound sight +3 (two skills)", spells: [5, 4, 3, "-", "-", "-"] },
    { level: 10, bab: 7, fort: 3, ref: 7, will: 3, special: "Infinite worlds (4th-level spells)", spells: [5, 4, 3, 2, "-", "-"] },
    { level: 11, bab: 8, fort: 3, ref: 7, will: 3, special: "Paradigm shift", spells: [5, 4, 4, 2, "-", "-"] },
    { level: 12, bab: 9, fort: 4, ref: 8, will: 4, special: "Alternate outcome 2/day, compound sight +4", spells: [5, 5, 4, 3, "-", "-"] },
    { level: 13, bab: 9, fort: 4, ref: 8, will: 4, special: "Infinite worlds (5th-level spells)", spells: [5, 5, 4, 3, 2, "-"] },
    { level: 14, bab: 10, fort: 4, ref: 9, will: 4, special: "Paradigm shift", spells: [5, 5, 4, 4, 2, "-"] },
    { level: 15, bab: 11, fort: 5, ref: 9, will: 5, special: "Compound sight +5", spells: [5, 5, 5, 4, 3, "-"] },
    { level: 16, bab: 12, fort: 5, ref: 10, will: 5, special: "Infinite worlds (6th-level spells)", spells: [5, 5, 5, 4, 3, 2] },
    { level: 17, bab: 12, fort: 5, ref: 10, will: 5, special: "Paradigm shift", spells: [5, 5, 5, 4, 4, 2] },
    { level: 18, bab: 13, fort: 6, ref: 11, will: 6, special: "Alternate outcome 3/day, compound sight +6", spells: [5, 5, 5, 5, 4, 3] },
    { level: 19, bab: 14, fort: 6, ref: 11, will: 6, special: "Unfold existences", spells: [5, 5, 5, 5, 5, 4] },
    { level: 20, bab: 15, fort: 6, ref: 12, will: 6, special: "Paradigm shift, reality stutter", spells: [5, 5, 5, 5, 5, 5] }
]
};

export default classProgressionTable;
